name: Updating lambda edge function to aws
run-name: ⚙️ ${{ github.actor }} is uploading lambda@edge and infrastructure to aws

on:
  push:
    paths:
      - 'packages/routing-edge/src/**'
      - 'packages/routing-edge/template.yaml'
      - '.github/workflows/sam-pipeline.yml'
      - '!packages/routing-edge/src/routes/frontend-catalog.json'
    branches:
      - main

jobs:
  build-deploy-sam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build and Deploy SAM 
        run: | 
          cd ./packages/routing-edge
          sam build --use-container
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name mfe-on-the-edge --capabilities CAPABILITY_IAM --region us-east-1
